version: '3.8'
services: 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: 
      - backend
    volumes:
      - /frontend/node_modules
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - /backend/node_modules/bcrypt
      - ./backend:/backend 
    ports: 
      - "9000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

